export { default as List } from './List'
export { default as Dashboard } from './Dashboard'
export { default as Contacts } from './Contacts'
export { default as ListContact } from './Contacts/listContact'
export { default as AddContact } from './Contacts/addContact'
export { default as Types } from './Types'
export { default as AddTypes } from './Types/addTypes'
